### ISSUE TITLE
Tracking issue of GraphAr first Apache release

### ISSUE THREAD

**Issue by acezen** [apache/incubator-graphar#466]
### Describe the enhancement requested
[Incubator Releases Guide](https://incubator.apache.org/guides/releasemanagement.html#choice_of_disclaimers)

### Blockers
> Blockers are the tasks that must be completed before the release.

#### C++
- #476 
- #509 

#### Maven projects: Java & Scala
- #478 

#### Other
- [x] ensure all licenses issues has been addressed
     - #479 
     - #485 
- [x] #495 
- [x] Guide or scripts to verify the release source package
- [x] Scripts and action to sign signature and build release package
- [x] #510

#### Github Side
- [x] Bump version in project
  - [x] cpp
  - [x] scala
- [x] Update docs
- [x] Push release candidate tag to GitHub

#### ASF Side

- [x] Setup KEYS and upload to apache release dist
- [x] Create an ASF Release
- [x] Upload artifacts to the SVN dist repo
- [x] Close the Nexus staging repo

#### Voting

- [x] Start VOTE at GraphAr community
- [x] Start VOTE at Apache Incubator mail list

### Official Release

- [x] Push the release git tag
- [x] Publish artifacts to SVN RELEASE branch
- [x] Release Maven artifacts
- [x] Send the announcement

### Component(s)

Other

**Comment by SemyonSinchenko** [comment]
Are we going to have Maven and PyPi packages for spark/pyspark?

**Comment by acezen** [comment]
> Are we going to have Maven and PyPi packages for spark/pyspark?

This is what I want to discuss in the dev list. We can release a source release. But I think it's better to release the binary package if we can (which we should evaluate the current status wether spark/pyspark/java is ready for a binary release)

Since apache release process has  more concern about the knowledge copyright, we can be familiar with the release procedure through the first release.
