### ISSUE TITLE
Tracking release of Apache GraphAr(incubating) v0.13.0

### ISSUE THREAD

**Issue by Thespica** [apache/incubator-graphar#609]
### Describe the enhancement requested

# Describe the enhancement requested
[Incubator Releases Guide](https://incubator.apache.org/guides/releasemanagement.html#choice_of_disclaimers)

# Blockers
Blockers are the tasks that must be completed before the release.

## C++
- [x] #724  
- [x] #729 
## Maven projects: Java & Scala
- [x] #726

## pyspark
to be discussed

## Other

# Build Release

## Github Side
 - [x] Bump version in project
   - [x] cpp
   - [x] java-info
   - [x] java
   - [x] scala
   - [x] pyspark
 - [ ] Update docs
 - [x] Push release candidate tag to GitHub

## ASF Side
 - [x] Setup KEYS and upload to apache release dist
 - [x] Create an ASF Release
 - [x] Upload artifacts to the SVN dist repo
 - [ ] Close the Nexus staging repo

## Voting
 - [x] Start VOTE at GraphAr community
 - [x] Start VOTE at Apache Incubator mail list

## Official Release
 - [x] Push the release git tag
 - [x] Publish artifacts to SVN RELEASE branch
 - [ ] Release Maven artifacts
 - [x] Send the announcement

### Component(s)

Other
